<template>
  <AppLayout><Head :title="project.name" /><section class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/projects" class="text-sm font-bold text-[#e85d3f]">← Yangi qurilishlar</Link><div class="mt-5 overflow-hidden rounded-[32px] bg-[#222a25] text-white"><div class="relative min-h-[340px] p-7 sm:p-10"><img v-if="project.media?.length" :src="`/storage/${project.media[0].storage_path}`" :alt="project.name" class="absolute inset-0 h-full w-full object-cover opacity-35" /><div class="relative max-w-3xl"><div class="flex flex-wrap gap-2"><span class="badge">{{ stageLabel(project.stage) }}</span><span v-if="project.is_demo" class="badge">Demo</span></div><h1 class="mt-8 text-4xl font-black tracking-[-0.06em] sm:text-6xl">{{ project.name }}</h1><p class="mt-4 text-lg font-bold text-[#bedc79]">{{ project.developer_name }}</p><p class="mt-5 max-w-2xl leading-7 text-slate-200">{{ project.description }}</p><div class="mt-7 flex flex-wrap gap-5 text-sm font-semibold text-slate-300"><span>{{ project.district?.name_uz }}</span><span>{{ project.completion_text || 'Topshirish sanasi aniqlanmoqda' }}</span></div></div></div></div>
    <div class="mt-12 flex items-end justify-between gap-4"><div><p class="eyebrow">Sotuvdagi xonadonlar</p><h2 class="mt-2 text-3xl font-black">Mavjud takliflar</h2></div><button v-if="consultationAvailable" class="rounded-full bg-[#e85d3f] px-5 py-3 text-sm font-black text-white" @click="consultationOpen = true">Maslahat olish</button></div><div v-if="!project.listings?.length" class="surface mt-6 rounded-[26px] p-10 text-center text-slate-500">Hozircha sotuvdagi taklif yo‘q.</div><div class="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Link v-for="listing in project.listings" :key="listing.id" :href="`/listings/${listing.id}`" class="surface overflow-hidden rounded-[26px]"><div class="h-40 bg-slate-100"><img v-if="listing.media?.length" :src="`/storage/${listing.media[0].storage_path}`" :alt="listing.title" class="h-full w-full object-cover" /></div><div class="p-5"><h3 class="text-lg font-black">{{ listing.title }}</h3><p class="mt-3 text-2xl font-black text-[#e85d3f]">{{ money(listing.price, listing.currency) }}</p><p class="mt-2 text-sm text-slate-500">{{ listing.rooms || '—' }} xona · {{ listing.area_m2 || '—' }} m²</p></div></Link></div>
  </section>
  <div v-if="consultationOpen" class="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" @click.self="consultationOpen = false"><form class="surface w-full max-w-md rounded-[28px] p-6" @submit.prevent="submit"><div class="flex justify-between"><div><p class="eyebrow">{{ project.name }}</p><h2 class="mt-2 text-2xl font-black">Maslahat olish</h2></div><button type="button" @click="consultationOpen = false">✕</button></div><label class="mt-5 block"><span class="field-label">Ism</span><input v-model="form.name" class="field" required /><span class="error">{{ form.errors.name }}</span></label><label class="mt-4 block"><span class="field-label">Telefon</span><input v-model="form.phone" class="field" required placeholder="+998 90 123 45 67" /><span class="error">{{ form.errors.phone }}</span></label><label class="mt-4 block"><span class="field-label">Savol yoki izoh</span><textarea v-model="form.message" rows="4" class="field" /></label><button class="mt-5 w-full rounded-2xl bg-[#e85d3f] px-5 py-3 text-sm font-black text-white disabled:opacity-50" :disabled="form.processing">{{ form.processing ? 'Yuborilmoqda…' : 'Murojaat yuborish' }}</button></form></div>
  </AppLayout>
</template>
<script setup>
import { ref } from 'vue'; import { Head, Link, useForm, usePage } from '@inertiajs/vue3'; import AppLayout from '../Layouts/AppLayout.vue';
const props = defineProps({ project: Object, consultationAvailable: Boolean }); const user = usePage().props.auth?.user; const consultationOpen = ref(false); const form = useForm({ name: user?.name || '', phone: user?.phone || '', message: '', idempotency_key: crypto.randomUUID() });
function submit() { form.post(`/projects/${props.project.id}/requests`, { preserveScroll: true }); }
function money(value, currency) { return value == null ? 'So‘rov bo‘yicha' : `${new Intl.NumberFormat('uz-UZ').format(value)} ${currency}`; }
function stageLabel(value) { return { planning: 'Rejalashtirilmoqda', building: 'Qurilmoqda', completed: 'Tayyor' }[value] || 'Yangi loyiha'; }
</script>
<style scoped>.badge { @apply rounded-full bg-white/10 px-3 py-1 text-xs font-black backdrop-blur; }.field-label { @apply mb-1.5 block text-xs font-black uppercase tracking-wider text-slate-500; }.field { @apply w-full rounded-xl border-black/10 bg-white/70 px-3 py-2.5 text-sm dark:border-white/10 dark:bg-white/5; }.error { @apply mt-1 block text-xs font-semibold text-red-600; }</style>
