<template>
  <AppLayout><Head title="Habarlar" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">E’lon muallifi</p><h1 class="page-title">Habarlar</h1><p class="mt-3 text-slate-600 dark:text-slate-300">E’lonlaringizga yuborilgan murojaatlar va ularning holati.</p></div><Link href="/account/requests" class="text-sm font-bold text-[#e85d3f]">Men yuborganlar →</Link></div>
    <div v-if="$page.props.flash?.success" class="mt-6 rounded-2xl bg-emerald-100 px-4 py-3 text-sm font-semibold text-emerald-900">{{ $page.props.flash.success }}</div><div v-if="!requests.length" class="surface mt-8 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Hozircha habar yo‘q</h2><p class="mt-2 text-slate-500">Foydalanuvchi e’loningizga murojaat yuborganda shu yerda ko‘rinadi.</p></div>
    <div class="mt-8 space-y-4"><article v-for="item in requests" :key="item.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><span class="status">{{ statusLabel(item.status) }}</span><h2 class="mt-3 text-xl font-black">{{ item.listing?.title }}</h2><p class="mt-2 text-sm text-slate-500">{{ item.requester?.name }} · {{ item.phone }}</p><p v-if="item.message" class="mt-3 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{{ item.message }}</p><p class="mt-3 text-sm font-semibold">Taklif: {{ dateTime(item) }} · {{ item.occupants_count || 1 }} kishi</p></div><div class="flex max-w-sm flex-wrap gap-2"><button v-if="item.status === 'new'" class="action bg-emerald-600 text-white" @click="change(item.id, 'accepted')">Qabul qilish</button><button v-if="item.status === 'new'" class="action bg-amber-100 text-amber-800" @click="openAlternative(item)">Boshqa vaqt</button><button v-if="['new','alternative_proposed'].includes(item.status)" class="action bg-red-50 text-red-700" @click="openDecision(item, 'rejected')">Rad etish</button><button v-if="item.status === 'accepted'" class="action bg-[#e85d3f] text-white" @click="openDecision(item, 'completed')">Yakunlash</button></div></div><details class="mt-5 border-t border-black/10 pt-4 dark:border-white/10"><summary class="cursor-pointer text-sm font-bold text-slate-500">Holatlar tarixi · {{ item.events?.length || 0 }}</summary><ol class="mt-3 space-y-3"><li v-for="event in item.events" :key="event.id" class="border-l-2 border-[#e85d3f]/30 pl-3 text-sm"><p class="font-bold">{{ statusLabel(event.to_status) }}</p><p class="text-xs text-slate-500">{{ event.actor?.name }} · {{ formatDateTime(event.created_at) }}</p><p v-if="event.comment" class="mt-1 text-slate-600 dark:text-slate-300">{{ event.comment }}</p></li></ol></details></article></div>
  </section>
  <div v-if="dialog" class="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" @click.self="dialog = null"><form class="surface w-full max-w-md rounded-[28px] p-6" @submit.prevent="submitDialog"><div class="flex justify-between gap-4"><h2 class="text-2xl font-black">{{ dialog.status === 'alternative_proposed' ? 'Boshqa vaqt taklif qilish' : dialog.status === 'rejected' ? 'Rad etish' : 'Murojaatni yakunlash' }}</h2><button type="button" @click="dialog = null">✕</button></div><template v-if="dialog.status === 'alternative_proposed'"><label class="mt-5 block"><span class="field-label">Sana</span><input v-model="decision.proposed_at" type="date" :min="today" class="field" required /></label><div class="mt-3 grid grid-cols-2 gap-3"><label><span class="field-label">Boshlanish</span><input v-model="decision.time_start" type="time" class="field" /></label><label><span class="field-label">Tugash</span><input v-model="decision.time_end" type="time" class="field" /></label></div></template><label class="mt-4 block"><span class="field-label">Izoh</span><textarea v-model="decision.comment" rows="3" class="field" :required="dialog.status === 'rejected'" /></label><button class="mt-4 w-full rounded-2xl bg-[#e85d3f] px-5 py-3 text-sm font-black text-white">Saqlash</button></form></div>
  </AppLayout>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { Head, Link, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
defineProps({ requests: { type: Array, default: () => [] } }); const today = new Date().toISOString().slice(0, 10); const dialog = ref(null); const decision = reactive({ proposed_at: '', time_start: '', time_end: '', comment: '' });
function change(id, status, data = {}) { router.patch(`/requests/${id}/status`, { status, ...data }, { preserveScroll: true }); }
function openAlternative(item) { Object.assign(decision, { proposed_at: item.proposed_at?.slice(0,10) || today, time_start: item.time_start?.slice(0,5) || '', time_end: item.time_end?.slice(0,5) || '', comment: '' }); dialog.value = { id: item.id, status: 'alternative_proposed' }; }
function openDecision(item, status) { Object.assign(decision, { proposed_at: '', time_start: '', time_end: '', comment: '' }); dialog.value = { id: item.id, status }; }
function submitDialog() { change(dialog.value.id, dialog.value.status, { ...decision }); dialog.value = null; }
function statusLabel(s) { return { new:'Yangi', accepted:'Qabul qilindi', alternative_proposed:'Boshqa vaqt taklif qilindi', rejected:'Rad etildi', cancelled:'Bekor qilindi', completed:'Yakunlandi' }[s] || s; }
function formatDateTime(value) { return value ? new Intl.DateTimeFormat('uz-UZ', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function dateTime(item) { if (!item.proposed_at) return 'Kelishiladi'; const date = new Intl.DateTimeFormat('uz-UZ').format(new Date(item.proposed_at)); return `${date}${item.time_start ? `, ${item.time_start.slice(0,5)}` : ''}`; }
</script>
<style scoped>.action { @apply rounded-xl px-3 py-2 text-xs font-black; }.status { @apply inline-flex rounded-full bg-[#bedc79]/35 px-3 py-1 text-[11px] font-black uppercase tracking-wider text-[#40551d]; }.field-label { @apply mb-1 block text-xs font-black uppercase tracking-wider text-slate-500; }.field { @apply w-full rounded-xl border-black/10 bg-white/70 px-3 py-2.5 text-sm dark:border-white/10 dark:bg-white/5; }</style>
