<template>
  <AppLayout><Head title="Kelgan murojaatlar" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-blue-600">E’lon muallifi</p><h1 class="mt-2 text-4xl font-black tracking-[-0.05em] text-slate-950">Kelgan murojaatlar</h1></div><Link href="/account/requests" class="text-sm font-semibold text-blue-600">Men yuborganlar →</Link></div><div v-if="!requests.length" class="mt-8 rounded-[26px] border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">Hozircha murojaat kelmagan.</div><div class="mt-8 space-y-4"><article v-for="item in requests" :key="item.id" class="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-blue-600">{{ statusLabel(item.status) }}</p><h2 class="mt-1 text-lg font-bold text-slate-950">{{ item.listing?.title }}</h2><p class="mt-1 text-sm text-slate-500">{{ item.requester?.name }} · {{ item.phone }}</p></div><div class="flex flex-wrap gap-2"><button v-if="item.status === 'new'" class="action bg-emerald-600 text-white" @click="change(item.id, 'accepted')">Qabul qilish</button><button v-if="item.status === 'new'" class="action bg-amber-100 text-amber-800" @click="change(item.id, 'alternative_proposed')">Boshqa vaqt</button><button v-if="['new','alternative_proposed'].includes(item.status)" class="action bg-red-50 text-red-700" @click="change(item.id, 'rejected')">Rad etish</button><button v-if="item.status === 'accepted'" class="action bg-blue-600 text-white" @click="change(item.id, 'completed')">Yakunlash</button></div></div></article></div></section></AppLayout>
</template>
<script setup>
import { Head, Link, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
defineProps({ requests: { type: Array, default: () => [] } });
function change(id, status) { router.patch(`/requests/${id}/status`, { status }, { preserveScroll: true }); }
function statusLabel(s) { return { new:'Yangi', accepted:'Qabul qilindi', alternative_proposed:'Boshqa vaqt taklif qilindi', rejected:'Rad etildi', cancelled:'Bekor qilindi', completed:'Yakunlandi' }[s] || s; }
</script>
<style scoped>.action { @apply rounded-xl px-3 py-2 text-xs font-bold; }</style>
