<template>
  <AppLayout><Head title="Mening murojaatlarim" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Shaxsiy kabinet</p><h1 class="page-title">Mening murojaatlarim</h1></div><Link href="/account/inbox" class="text-sm font-bold text-[#e85d3f]">Habarlar →</Link></div><div v-if="!requests.length" class="surface mt-8 rounded-[28px] p-12 text-center"><h2 class="font-black">Hozircha murojaatlar yo‘q</h2><p class="mt-2 text-slate-500">Katalogdagi e’londan ko‘rish uchun murojaat yuboring.</p><Link href="/catalog" class="mt-3 inline-block font-bold text-[#e85d3f]">Katalogni ochish</Link></div><div class="mt-8 grid gap-4 md:grid-cols-2"><article v-for="item in requests" :key="item.id" class="surface rounded-[26px] p-5"><div class="flex items-start justify-between gap-3"><div><span class="status">{{ statusLabel(item.status) }}</span><Link :href="`/listings/${item.listing_id}`" class="mt-3 block text-lg font-black hover:text-[#e85d3f]">{{ item.listing?.title || 'E’lon' }}</Link><p class="mt-1 text-sm text-slate-500">{{ item.listing?.district?.name_uz }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">#{{ item.id }}</span></div><div class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Ko‘rish vaqti</p><p class="mt-1 font-semibold">{{ dateTime(item) }}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Qabul qiluvchi</p><p class="mt-1 font-semibold">{{ item.recipient?.name }}</p></div></div><div v-if="item.status === 'alternative_proposed'" class="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><p class="font-bold">Yangi vaqt taklif qilindi</p><p class="mt-1">{{ dateTime(item) }}</p><button class="mt-3 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white" @click="change(item.id, 'accepted')">Qabul qilish</button></div><button v-if="['new','alternative_proposed','accepted'].includes(item.status)" class="mt-4 text-sm font-bold text-red-600" @click="change(item.id, 'cancelled')">Murojaatni bekor qilish</button><details class="mt-5 border-t border-black/10 pt-4 dark:border-white/10"><summary class="cursor-pointer text-sm font-bold text-slate-500">Holatlar tarixi</summary><ol class="mt-3 space-y-3"><li v-for="event in item.events" :key="event.id" class="border-l-2 border-[#e85d3f]/30 pl-3 text-sm"><p class="font-bold">{{ statusLabel(event.to_status) }}</p><p class="text-xs text-slate-500">{{ event.actor?.name }} · {{ formatDateTime(event.created_at) }}</p><p v-if="event.comment" class="mt-1">{{ event.comment }}</p></li></ol></details></article></div></section></AppLayout>
</template>
<script setup>
import { Head, Link, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue'; defineProps({ requests: { type: Array, default: () => [] } });
function change(id, status) { router.patch(`/requests/${id}/status`, { status }, { preserveScroll: true }); }
function statusLabel(s) { return { new:'Yangi', accepted:'Qabul qilindi', alternative_proposed:'Boshqa vaqt taklif qilindi', rejected:'Rad etildi', cancelled:'Bekor qilindi', completed:'Yakunlandi' }[s] || s; }
function formatDateTime(value) { return value ? new Intl.DateTimeFormat('uz-UZ', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function dateTime(item) { if (!item.proposed_at) return 'Kelishiladi'; const date = new Intl.DateTimeFormat('uz-UZ').format(new Date(item.proposed_at)); return `${date}${item.time_start ? `, ${item.time_start.slice(0,5)}` : ''}`; }
</script>
<style scoped>.status { @apply inline-flex rounded-full bg-[#bedc79]/35 px-3 py-1 text-[11px] font-black uppercase tracking-wider text-[#40551d]; }</style>
