<template>
  <AppLayout><Head title="Moderatsiya" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
    <p class="eyebrow">Administrator</p><h1 class="page-title">Moderatsiya markazi</h1><p class="mt-3 text-slate-600 dark:text-slate-300">E’lonlar va foydalanuvchi shikoyatlarini bir joyda ko‘rib chiqing.</p>
    <div class="mt-8 flex gap-2"><button class="tab" :class="tab === 'listings' ? 'tab-active' : ''" @click="tab = 'listings'">E’lonlar · {{ listings.total }}</button><button class="tab" :class="tab === 'reports' ? 'tab-active' : ''" @click="tab = 'reports'">Shikoyatlar · {{ reports.length }}</button></div>

    <template v-if="tab === 'listings'"><div v-if="!listings.data.length" class="surface mt-6 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Navbat bo‘sh</h2></div><div class="mt-6 space-y-4"><article v-for="item in listings.data" :key="item.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-xs font-black uppercase tracking-wider text-[#e85d3f]">#{{ item.id }} · {{ item.district?.name_uz }}</p><h2 class="mt-2 text-xl font-black">{{ item.title }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{{ item.description }}</p><p class="mt-3 text-sm font-bold">Muallif: {{ item.owner?.name }} · {{ item.owner?.email }}</p></div><div class="w-full lg:w-80"><textarea v-model="reasons[item.id]" rows="2" class="field" placeholder="Rad etish/bloklash sababi" /><div class="mt-2 grid grid-cols-3 gap-2"><button class="action bg-emerald-600 text-white" @click="decide(item.id, 'approved')">Tasdiqlash</button><button class="action bg-amber-100 text-amber-900" @click="decide(item.id, 'rejected')">Rad etish</button><button class="action bg-red-100 text-red-800" @click="decide(item.id, 'blocked')">Bloklash</button></div></div></div></article></div></template>

    <template v-else><div v-if="!reports.length" class="surface mt-6 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Yangi shikoyatlar yo‘q</h2></div><div class="mt-6 space-y-4"><article v-for="report in reports" :key="report.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="grid gap-5 lg:grid-cols-[1fr_340px]"><div><p class="text-xs font-black uppercase tracking-wider text-red-600">{{ reportReason(report.reason) }} · #{{ report.id }}</p><Link :href="`/listings/${report.listing_id}`" class="mt-2 block text-xl font-black hover:text-[#e85d3f]">{{ report.listing?.title }}</Link><p v-if="report.comment" class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{{ report.comment }}</p><p class="mt-3 text-xs text-slate-500">Yubordi: {{ report.reporter?.name }} · {{ report.reporter?.email }}</p></div><div><textarea v-model="resolutions[report.id]" rows="3" class="field" placeholder="Administrator qarori" /><label class="mt-2 flex items-center gap-2 text-sm font-semibold"><input v-model="blocks[report.id]" type="checkbox" class="rounded text-red-600" /> E’lonni bloklash</label><div class="mt-3 grid grid-cols-2 gap-2"><button class="action bg-red-600 text-white" @click="resolveReport(report.id, 'resolved')">Tasdiqlash</button><button class="action bg-slate-100 text-slate-700" @click="resolveReport(report.id, 'dismissed')">Asossiz</button></div></div></div></article></div></template>
  </section></AppLayout>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { Head, Link, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
defineProps({ listings: Object, reports: { type: Array, default: () => [] } }); const tab = ref('listings'); const reasons = reactive({}); const resolutions = reactive({}); const blocks = reactive({});
function decide(id, status) { router.patch(`/admin/moderation/${id}`, { status, reason: reasons[id] || null }, { preserveScroll: true }); }
function resolveReport(id, status) { router.patch(`/admin/reports/${id}`, { status, resolution: resolutions[id] || '', block_listing: Boolean(blocks[id]) }, { preserveScroll: true }); }
function reportReason(value) { return { incorrect: 'Noto‘g‘ri ma’lumot', unavailable: 'Mavjud emas', fraud: 'Firibgarlik', duplicate: 'Takroriy e’lon', other: 'Boshqa sabab' }[value] || value; }
</script>
<style scoped>.field { @apply w-full rounded-xl border-black/10 bg-white/70 px-3 py-2 text-sm dark:border-white/10 dark:bg-white/5; }.action { @apply rounded-xl px-2 py-2 text-xs font-black disabled:opacity-50; }.tab { @apply rounded-full border border-black/10 px-4 py-2 text-sm font-black text-slate-500 dark:border-white/10; }.tab-active { @apply border-[#e85d3f] bg-[#e85d3f] text-white; }</style>
