<template>
  <AppLayout><Head title="Moderatsiya" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><p class="eyebrow">Administrator</p><h1 class="page-title">Moderatsiya navbati</h1><p class="mt-3 text-slate-600 dark:text-slate-300">E’lon shartlarini tekshirib, sabab bilan qaror qabul qiling.</p><div v-if="!listings.data.length" class="surface mt-8 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Navbat bo‘sh</h2></div><div class="mt-8 space-y-4"><article v-for="item in listings.data" :key="item.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-xs font-black uppercase tracking-wider text-[#e85d3f]">#{{ item.id }} · {{ item.district?.name_uz }}</p><h2 class="mt-2 text-xl font-black">{{ item.title }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{{ item.description }}</p><p class="mt-3 text-sm font-bold">Muallif: {{ item.owner?.name }} · {{ item.owner?.email }}</p></div><div class="w-full lg:w-80"><textarea v-model="reasons[item.id]" rows="2" class="field" placeholder="Rad etish/bloklash sababi" /><div class="mt-2 grid grid-cols-3 gap-2"><button class="action bg-emerald-600 text-white" @click="decide(item.id, 'approved')">Tasdiqlash</button><button class="action bg-amber-100 text-amber-900" @click="decide(item.id, 'rejected')">Rad etish</button><button class="action bg-red-100 text-red-800" @click="decide(item.id, 'blocked')">Bloklash</button></div></div></div></article></div></section></AppLayout>
</template>
<script setup>
import { reactive } from 'vue'; import { Head, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
defineProps({ listings: Object }); const reasons = reactive({});
function decide(id, status) { router.patch(`/admin/moderation/${id}`, { status, reason: reasons[id] || null }, { preserveScroll: true }); }
</script>
<style scoped>.field { @apply w-full rounded-xl border-black/10 bg-white/70 px-3 py-2 text-sm dark:border-white/10 dark:bg-white/5; }.action { @apply rounded-xl px-2 py-2 text-xs font-black; }</style>
