<template>
  <AppLayout><Head title="Moderatsiya" /><section class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
    <p class="eyebrow">Administrator</p><h1 class="page-title">Moderatsiya markazi</h1><p class="mt-3 text-slate-600 dark:text-slate-300">E’lonlar va foydalanuvchi shikoyatlarini bir joyda ko‘rib chiqing.</p>
    <div class="mt-8 flex gap-2 overflow-x-auto pb-2"><button class="tab" :class="tab === 'listings' ? 'tab-active' : ''" @click="tab = 'listings'">E’lonlar · {{ listings.total }}</button><button class="tab" :class="tab === 'reports' ? 'tab-active' : ''" @click="tab = 'reports'">Shikoyatlar · {{ reports.length }}</button><button class="tab" :class="tab === 'commissions' ? 'tab-active' : ''" @click="tab = 'commissions'">Komissiyalar · {{ commissions.length }}</button><button class="tab" :class="tab === 'settings' ? 'tab-active' : ''" @click="tab = 'settings'">Sozlamalar</button></div>

    <template v-if="tab === 'listings'"><div v-if="!listings.data.length" class="surface mt-6 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Navbat bo‘sh</h2></div><div class="mt-6 space-y-4"><article v-for="item in listings.data" :key="item.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-xs font-black uppercase tracking-wider text-[#e85d3f]">#{{ item.id }} · {{ item.district?.name_uz }}</p><h2 class="mt-2 text-xl font-black">{{ item.title }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{{ item.description }}</p><p class="mt-3 text-sm font-bold">Muallif: {{ item.owner?.name }} · {{ item.owner?.email }}</p></div><div class="w-full lg:w-80"><textarea v-model="reasons[item.id]" rows="2" class="field" placeholder="Rad etish/bloklash sababi" /><div class="mt-2 grid grid-cols-3 gap-2"><button class="action bg-emerald-600 text-white" @click="decide(item.id, 'approved')">Tasdiqlash</button><button class="action bg-amber-100 text-amber-900" @click="decide(item.id, 'rejected')">Rad etish</button><button class="action bg-red-100 text-red-800" @click="decide(item.id, 'blocked')">Bloklash</button></div></div></div></article></div></template>

    <template v-else-if="tab === 'reports'"><div v-if="!reports.length" class="surface mt-6 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Yangi shikoyatlar yo‘q</h2></div><div class="mt-6 space-y-4"><article v-for="report in reports" :key="report.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="grid gap-5 lg:grid-cols-[1fr_340px]"><div><p class="text-xs font-black uppercase tracking-wider text-red-600">{{ reportReason(report.reason) }} · #{{ report.id }}</p><Link :href="`/listings/${report.listing_id}`" class="mt-2 block text-xl font-black hover:text-[#e85d3f]">{{ report.listing?.title }}</Link><p v-if="report.comment" class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{{ report.comment }}</p><p class="mt-3 text-xs text-slate-500">Yubordi: {{ report.reporter?.name }} · {{ report.reporter?.email }}</p></div><div><textarea v-model="resolutions[report.id]" rows="3" class="field" placeholder="Administrator qarori" /><label class="mt-2 flex items-center gap-2 text-sm font-semibold"><input v-model="blocks[report.id]" type="checkbox" class="rounded text-red-600" /> E’lonni bloklash</label><div class="mt-3 grid grid-cols-2 gap-2"><button class="action bg-red-600 text-white" @click="resolveReport(report.id, 'resolved')">Tasdiqlash</button><button class="action bg-slate-100 text-slate-700" @click="resolveReport(report.id, 'dismissed')">Asossiz</button></div></div></div></article></div></template>

    <template v-else-if="tab === 'commissions'"><div v-if="!commissions.length" class="surface mt-6 rounded-[28px] p-12 text-center"><h2 class="text-xl font-black">Hozircha yakunlangan kelishuv yo‘q</h2></div><div class="mt-6 space-y-4"><article v-for="item in commissions" :key="item.id" class="surface rounded-[26px] p-5 sm:p-6"><div class="grid gap-5 lg:grid-cols-[1fr_340px]"><div><p class="text-xs font-black uppercase tracking-wider text-[#e85d3f]">{{ item.deal_type === 'sale' ? 'Sotuv' : 'Ijara' }} · {{ item.rate_percent }}%</p><h2 class="mt-2 text-xl font-black">{{ item.listing?.title }}</h2><p class="mt-2 text-sm text-slate-500">To‘lovchi: {{ item.payer?.name }} · {{ item.payer?.email }}</p><p class="mt-4 text-2xl font-black">{{ money(item.commission_amount, item.currency) }}</p><p class="mt-1 text-xs text-slate-500">Kelishuv summasi: {{ money(item.deal_amount, item.currency) }}</p></div><div><select v-model="item.status" class="field"><option value="pending">To‘lov kutilmoqda</option><option value="paid">To‘langan</option><option value="cancelled">Bekor qilingan</option></select><textarea v-model="notes[item.id]" rows="2" class="field mt-2" placeholder="Administrator izohi" /><button class="action mt-2 w-full bg-slate-950 text-white dark:bg-white dark:text-slate-950" @click="saveCommission(item)">Saqlash</button></div></div></article></div></template>

    <template v-else><form class="surface mt-6 max-w-2xl rounded-[28px] p-5 sm:p-7" @submit.prevent="saveSettings"><h2 class="text-xl font-black">Platforma daromad sozlamalari</h2><p class="mt-2 text-sm text-slate-500">Foizlar keyingi yakunlanadigan kelishuvlarga qo‘llanadi.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><label><span class="field-label">Ijara komissiyasi, %</span><input v-model="settingsForm.rent_commission_percent" type="number" min="0" max="100" step="0.01" class="field" /></label><label><span class="field-label">Sotuv komissiyasi, %</span><input v-model="settingsForm.sale_commission_percent" type="number" min="0" max="100" step="0.01" class="field" /></label><label class="sm:col-span-2"><span class="field-label">E’lonni necha kunda tasdiqlash kerak?</span><input v-model="settingsForm.listing_confirmation_days" type="number" min="1" max="30" class="field" /></label></div><button class="mt-5 rounded-xl bg-[#e85d3f] px-5 py-3 text-sm font-black text-white">Sozlamalarni saqlash</button></form></template>
  </section></AppLayout>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { Head, Link, router } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
const props = defineProps({ listings: Object, reports: { type: Array, default: () => [] }, commissions: { type: Array, default: () => [] }, settings: Object }); const tab = ref('listings'); const reasons = reactive({}); const resolutions = reactive({}); const blocks = reactive({}); const notes = reactive({}); const settingsForm = reactive({ ...props.settings });
function decide(id, status) { router.patch(`/admin/moderation/${id}`, { status, reason: reasons[id] || null }, { preserveScroll: true }); }
function resolveReport(id, status) { router.patch(`/admin/reports/${id}`, { status, resolution: resolutions[id] || '', block_listing: Boolean(blocks[id]) }, { preserveScroll: true }); }
function saveCommission(item) { router.patch(`/admin/commissions/${item.id}`, { status: item.status, admin_note: notes[item.id] || null }, { preserveScroll: true }); }
function saveSettings() { router.patch('/admin/platform-settings', settingsForm, { preserveScroll: true }); }
function money(value, currency) { return value == null ? 'Summa ko‘rsatilmagan' : `${new Intl.NumberFormat('uz-UZ').format(value)} ${currency}`; }
function reportReason(value) { return { incorrect: 'Noto‘g‘ri ma’lumot', unavailable: 'Mavjud emas', fraud: 'Firibgarlik', duplicate: 'Takroriy e’lon', other: 'Boshqa sabab' }[value] || value; }
</script>
<style scoped>.field-label { @apply mb-1.5 block text-xs font-black uppercase tracking-wider text-slate-500; }.field { @apply w-full rounded-xl border-black/10 bg-white/70 px-3 py-2 text-sm dark:border-white/10 dark:bg-white/5; }.action { @apply rounded-xl px-2 py-2 text-xs font-black disabled:opacity-50; }.tab { @apply shrink-0 rounded-full border border-black/10 px-4 py-2 text-sm font-black text-slate-500 dark:border-white/10; }.tab-active { @apply border-[#e85d3f] bg-[#e85d3f] text-white; }</style>
