<template>
  <GuestLayout><Head title="Ro‘yxatdan o‘tish" /><section class="surface rounded-[32px] p-6 sm:p-9">
    <p class="text-xs font-black uppercase tracking-[0.18em] text-[#e85d3f]">Yangi hisob</p><h2 class="mt-3 text-4xl font-black tracking-[-0.055em]">Ro‘yxatdan o‘tish</h2><p class="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-400">Uy qidiring yoki o‘z e’loningizni joylashtiring.</p>
    <form class="mt-7 space-y-4" @submit.prevent="submit"><label class="block"><span class="field-label">Ism</span><input v-model="form.name" class="field" autocomplete="name" autofocus required placeholder="Ismingiz" /><span class="error">{{ form.errors.name }}</span></label><label class="block"><span class="field-label">Telefon</span><input v-model="form.phone" type="tel" class="field" autocomplete="tel" placeholder="+998 90 123 45 67" /><span class="error">{{ form.errors.phone }}</span></label><label class="block"><span class="field-label">Email</span><input v-model="form.email" type="email" class="field" autocomplete="username" required placeholder="name@example.com" /><span class="error">{{ form.errors.email }}</span></label><div class="grid gap-4 sm:grid-cols-2"><label><span class="field-label">Parol</span><input v-model="form.password" type="password" class="field" autocomplete="new-password" required /><span class="error">{{ form.errors.password }}</span></label><label><span class="field-label">Parolni takrorlang</span><input v-model="form.password_confirmation" type="password" class="field" autocomplete="new-password" required /></label></div><button type="submit" class="w-full rounded-2xl bg-[#e85d3f] px-5 py-3.5 text-sm font-black text-white shadow-lg shadow-orange-900/15 transition hover:-translate-y-0.5 disabled:opacity-50" :disabled="form.processing">{{ form.processing ? 'Yaratilmoqda…' : 'Hisob yaratish' }}</button></form>
    <p class="mt-6 text-center text-sm text-slate-500 dark:text-slate-400">Hisobingiz bormi? <Link href="/login" class="font-black text-slate-950 underline decoration-[#e85d3f] decoration-2 underline-offset-4 dark:text-white">Kirish</Link></p>
  </section></GuestLayout>
</template>
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3'; import GuestLayout from '../../Layouts/GuestLayout.vue';
const form = useForm({ name: '', phone: '', email: '', password: '', password_confirmation: '' }); function submit() { form.post('/register', { onFinish: () => form.reset('password', 'password_confirmation') }); }
</script>
<style scoped>.field-label { @apply mb-1.5 block text-xs font-black uppercase tracking-[0.12em] text-slate-500 dark:text-slate-400; }.field { @apply w-full rounded-2xl border-black/10 bg-white/75 px-4 py-3 text-sm font-semibold text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#e85d3f] focus:ring-4 focus:ring-[#e85d3f]/10 dark:border-white/10 dark:bg-white/5 dark:text-white; }.error { @apply mt-1.5 block text-xs font-semibold text-red-600; }</style>
